---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Global
- type: document
  path: site/global.md
  label: Global
- type: heading
  label: Pages
- type: document
  path: site/index.md
  label: Home
- type: directory
  path: site/testimonials
  label: Testimonials
  create: documents
  match: "*"
  templates:
  - testimonial
- type: document
  path: contact.md
  label: Contact
  match: "**/*"
upload_dir: public/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
