---
label: Global config
hide_body: true
fields:
- type: text
  name: site-name
  label: Site name
- type: list
  name: nav
  label: Navigation
  config:
    use_select: false
- name: footer
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Footer
