---
label: Global config
hide_body: true
fields:
- type: text
  name: site-name
  label: Site name
- type: list
  name: nav
  label: Navigation
  config:
    use_select: false
- name: nav2
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: documents
      section: ''
      file: site/index.md
      path: title
  label: Nav
