---
label: Product
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
    min: 0
    max: 200
  label: Title
- type: datetime
  name: publish_date
  label: Publish date
  default: now
- type: boolean
  name: published
  label: Published
- name: product_images
  type: image_gallery
  config: {}
  label: Product images
