---
label: Product
hide_body: false
fields:
- type: field_group
  name: title
  label: Title
  fields:
  - type: text
    name: english
    label: English
  - type: text
    name: te_reo_maori
    label: Te Reo Māori
- type: datetime
  name: publish_date
  label: Publish date
  default: now
- type: boolean
  name: published
  label: Published
- name: product_images
  type: image_gallery
  config: {}
  label: Product images
